### ISSUE TITLE
Caching performance impact on web applications

### ISSUE THREAD

**Issue by marcinwadon** [stephank/docker-for-mac-nfs#3]
Hello everyone,

I faced with the issue explained here: [https://github.com/mitchellh/vagrant/issues/4204](https://github.com/mitchellh/vagrant/issues/4204) (files updated on the host propagate to docker container too long)

To solve this you have to edit `extra/etc/init.d/usermount` and add `actimeo=2` in line 14.
```mount -t nfs -o actimeo=2,noacl,noatime,nolock,async 192.168.65.1:/Users /Users```, then recreate and use new `initrd.img` (steps from README)

**Comment by stephank** [comment]
Thanks for looking into this!

I've added the option, though the whole thing should probably be configurable. :)
