### ISSUE TITLE
Broken in 1.13.0

### ISSUE THREAD

**Issue by stephank** [stephank/docker-for-mac-nfs#4]
Even when commenting out the modifications, and simply repacking the initrd, Docker fails to start. Something changed in the initrd format, (or we were missing a detail all along.)

Interesting is that `zcat` reports that there's some trailing data.

**Comment by stephank** [comment]
The trailing data appears to be another gzipped cpio archive.

I've tried preserving the trailing data, and using Linux (non-BSD) cpio utils to create our own initrd, but that doesn't seem to help any so far.

**Comment by stephank** [comment]
Looks like importing the initrd as a Docker image was breaking things. Should be fixed as of a1e9ba13256cbfc4dc9f1c2ebe8d98cf9503a394!

**Comment by snoe** [comment]
We're getting the following error, is it possible the grep are not stable?
@stephank 

```
++ xxd -p -c 4 -s 4 /Applications/Docker.app/Contents/Resources/moby/initrd.img
++ grep -n -m 1 1f8b0800
++ cut -f 1 -d :
+ DWORD_OFFSET=
+ OFFSET=0
+ dd if=/Applications/Docker.app/Contents/Resources/moby/initrd.img of=tail.bin bs=0 skip=1
dd: bs must be between 1 and 9223372036854775807
```

**Comment by stephank** [comment]
@snoe I think that happens because the initrd.img is already modified? Which version of Docker for Mac are you using?

The grep fails because the start of the trailing second archive is no longer 4-byte aligned. (Though I'm not sure if that means I'm appending the tail incorrectly.)
